name = "bipulonline"
compatibility_date = "2026-02-09"

routes = [
  { pattern = "bipul.online", custom_domain = true, override_existing_dns_record = true },
  { pattern = "www.bipul.online", custom_domain = true, override_existing_dns_record = true }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
